version: 1

project_name: mev-commit-operator-cli
dist: /tmp/dist/mev-commit-operator-cli

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    dir: .
    main: ./cmd
    binary: "mev-commit-operator-cli"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

release:
  github:
    owner: primev
    name: mev-commit-operator-cli

  prerelease: auto

  name_template: "v{{ .Version }}"

  header: |
    ## MEV-Commit Operator CLI v{{ .Version }}

    This is a pre-release version of the MEV-Commit Operator CLI. Use with caution.

  footer: |
    **Full Changelog**: https://github.com/primev/mev-commit-operator-cli/compare/{{ .PreviousTag }}...{{ .Tag }}